package io.rtdi.appcontainer.designtimeobjects.sql;

public enum SQLScriptParserStates {
	SQL_TEXT,
	SLASH,
	LINE_COMMENT,
	BLOCK_COMMENT,
	BLOCK_COMMENT_END,
	STRING_ESCAPE_DOUBLE_QUOTE,
	STRING_ESCAPE_SINGLE_QUOTE,
	STRING_DOUBLE_QUOTE,
	STRING_SINGLE_QUOTE,
	DOLLAR_IN_DOUBLE_QUOTE,
	DOLLAR_IN_SINGLE_QUOTE,
	DOLLAR_IN_SQL_TEXT,
	AMPERSEND_IN_DOUBLE_QUOTE,
	AMPERSEND_IN_SINGLE_QUOTE,
	AMPERSEND_IN_SQL_TEXT,
	ALIAS_IN_DOUBLE_QUOTE,
	ALIAS_IN_SINGLE_QUOTE,
	ALIAS_IN_SQL_TEXT,
	VARIABLE_IN_DOUBLE_QUOTE,
	VARIABLE_IN_SINGLE_QUOTE,
	VARIABLE_IN_SQL_TEXT;

}
