FROM rtdi/connectorrootapp

LABEL maintainer="info@rtdi.io"

ADD https://github.com/rtdi/AppContainerRealm/releases/latest/download/dbrealmbase.jar ./lib
ADD https://github.com/rtdi/AppContainerRealm/releases/latest/download/sqlserverrealm.jar ./lib
ADD https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/11.2.2.jre17/mssql-jdbc-11.2.2.jre17.jar ./lib
ADD https://raw.githubusercontent.com/rtdi/AppContainer/master/docker/server-sqlserver.xml conf/server.xml
ADD https://github.com/rtdi/AppContainer/releases/latest/download/AppContainer.war ./webapps/

EXPOSE 8080
EXPOSE 8443


CMD ["appcontainer.sh", "run"]
