FROM rtdi/connectorrootapp

LABEL maintainer="info@rtdi.io"

ADD https://github.com/rtdi/AppContainerRealm/releases/latest/download/dbrealmbase.jar ./lib
ADD https://github.com/rtdi/AppContainerRealm/releases/latest/download/postgresrealm.jar ./lib
ADD https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.1/postgresql-42.5.1.jar ./lib
ADD https://raw.githubusercontent.com/rtdi/AppContainer/master/docker/server-postgres.xml conf/server.xml
ADD https://github.com/rtdi/AppContainer/releases/latest/download/AppContainer.war ./webapps/

EXPOSE 8080
EXPOSE 8443


CMD ["catalina.sh", "run"]
